[package]
name = "rust-kafka-test"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "*"
kafka = "*"

[[bin]]
name = "producer"
path = "src/producer.rs"

[[bin]]
name = "consumer"
path = "src/consumer.rs"
