version: '3'
services:
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,DOCKER_NET://:9094,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://127.0.0.1:9092,DOCKER_NET://kafka:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,DOCKER_NET:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
        - kafka-net
  init-kafka:
    image: apache/kafka
    depends_on:
      - kafka
    networks:
        - kafka-net
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      ./opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --list

      echo -e 'Creating kafka topics'
      ./opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic my-topic --replication-factor 1 --partitions 2

      echo -e 'Successfully created the following topics:'
      ./opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --list
      "
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    networks:
      - kafka-net
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka_0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
networks:
  kafka-net:
    driver: bridge